# des2pro = ("Created in:")
# des3pro = ("Directed by:")
# forupp = int((len(des1) + len(des2) + len(des3)) * 1.5)
# upp = "+" + "-" * forupp + "+"
# print(upp)
# print("|" + " " * forupp + "|")
# print("|" + " " * forupp + "|")
# print("|", des1.center(forupp - 2), "|" )
# print("|", des2pro.center(forupp - 2), "|" )
# print("|", des2.center(forupp - 2), "|" )
# print("|", des3pro.center(forupp - 2), "|" )
# print("|", des3.center(forupp - 2), "|" )
# print("|" + " " * forupp + "|")
# print("|" + " " * forupp + "|")
# print(upp)